name: mario_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - numpy=1.24.4
  - pytorch=2.2
  - torchvision=0.17
  - torchaudio=2.2
  - pytorch-cuda=11.8
  - pip=24.0
  - pip:
      - gym==0.19.0
      - gym-super-mario-bros==7.3.0
      - nes-py==8.2.1
      - opencv-python
      - tqdm
      - tensorboard
